gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl_update: true
    cookie:
        enabled: true
        path: /api/token/refresh
        http_only: true
        secure: false
        same_site: lax
